### ISSUE TITLE
InitialLatex issue

### ISSUE THREAD

**Issue by asadgulxar** [krirkrirk/react-math-keyboard#13]
How can we set initial Latex. I'm assigning a valid latex but it shows empty input field on initial render. here is my code 

`
  const MathInputComponent = () => {
      const [value1, setValue1] = useState();
    
      return (
          <>
              <MathInput
                  initialLatex="\\frac{\\int_a^b 2\\pi e^{2ix}\\cos(\\theta) \\gamma}{\\sum_2^9 i^2 - 1}"
                  setValue={setValue1}
                  divisionFormat="obelus"
              />
          </>
      );
  };

export default MathInputComponent;`

**Comment by krirkrirk** [comment]
Hello ! The mathquill's method MF.latex() seems to not work with string literals for whatever reason. Your issue should be fixed by surrounding your string with brackets : 

```jsx
<MathInput
              initialLatex={"\\frac{\\int_a^b 2\\pi e^{2ix}\\cos(\\theta) \\gamma}{\\sum_2^9 i^2 - 1}"}
     
          />
```

**Comment by asadgulxar** [comment]
@krirkrirk I've fixed the issue but don't have permission to push my branch and open a PR. Could you please update the project permissions to allow others to contribute?

I'm getting the following error

```
ERROR: Permission to krirkrirk/react-math-keyboard.git denied to asadgulxar.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
