### ISSUE TITLE
Auto Submission.

### ISSUE THREAD

**Issue by LuthandoMaqondo** [krirkrirk/react-math-keyboard#15]
I used the Mathfield as part of a form, I found that it automatically forced the form to submit when I clicked on the Math symbols on the virtual keyboard.

Is there way we can help prevent that or a setting I might be missing?

**Comment by krirkrirk** [comment]
Indeed the <button>s were missing a type="button" to prevent this behavior. 
This is fixed in @1.5.18. 
Thanks for your feedback !
