### ISSUE TITLE
tab Index support for multiple Math inputs

### ISSUE THREAD

**Issue by NJneeraj** [krirkrirk/react-math-keyboard#17]
I need tab support in the inputs..right now If I click on on input and press tab..it travels through each key on the keyboard..there should be an option if we want to go to next input

**Comment by krirkrirk** [comment]
Hi, 
This is possible version 1.5.28 by passing the prop `tabShouldSkipKeys = true` to the MathInput. 
Sorry for the delayed answer, we're very busy right now. 
Cheers

**Comment by NJneeraj** [comment]
> Hi, This is possible in version 1.5.28 by passing the prop `tabShouldSkipKeys = true` to the MathInput. Sorry for the delayed answer, we're very busy right now. Cheers

I used this prop on the math Input..But now...I am getting this error 
```
TypeError: l.replace is not a function
eval
node_modules\react-math-keyboard\dist\react-math-keyboard.js (2:250933)
```

**Comment by NJneeraj** [comment]
> Hi, This is possible in version 1.5.28 by passing the prop `tabShouldSkipKeys = true` to the MathInput. Sorry for the delayed answer, we're very busy right now. Cheers

Hii..Thanks for your response..It works perfectly.
Just one more thing...The types seems not to be working ..no intellisense for props.

**Comment by krirkrirk** [comment]
Yes, this is something I intended to fix a while ago but I'm now too busy on other projects...
The fix shouldn't be too hard, something must be broken in the webpack config. Any PR is welcomed !
In the future I plan on migrating to Rollup which seems miles better than the current stack. 
Cheers !
