### ISSUE TITLE
Custom embedded objects

### ISSUE THREAD

**Issue by asianvader** [krirkrirk/react-math-keyboard#9]
Hi @krirkrirk,
Thank you for developing this. Just wondering if there's any intention of adding .registerEmbed() experimental API method (https://docs.mathquill.com/en/latest/Api_Methods/#registerembedname-functionid-return-options-x)?

Thanks.

**Comment by krirkrirk** [comment]
Hi @asianvader ,
I believe it's already possible to achieve this. You can get a ref to the Mathquill input by doing something like this : 

```js
const ref = useRef();

<MathInput setMathfieldRef={(mathfield) => (ref.current = mathfield)} />
```
Then the whole Mathquill API is available via ref.current, so ref.current.registerEmbed() will work.

**Comment by asianvader** [comment]
Thanks for your quick reply @krirkrirk. Unfortunately, your suggesting didn't work for the `.registerEmbed()` method, but did work for the other experimental feature - `.dropEmbedded()`. I downloaded and delved more into your code and managed to find a way to register custom objects. In `mathInput.tsx` line 121 where you first declare Mathquill: `const MQ = window.MathQuill.getInterface(2)`. Changing the const to let, I was able to register a new object e.g:
```
MQ.registerEmbed("algebraA", function registerAlgebraA() {
      return {
        htmlString: `<span class="mq-algebra">&#97;</span>`,
        text: function text() {
          return "algebraa";
        },
        latex: function latex() {
          return "\\algebraA";
        },
      };
    });

```
Using your `example.tsx` as a playground, I added a custom button where the `mathFieldInstructions` are as follows:
```
mathfieldInstructions: {
                  content:
                    "\\embed{algebraA}",
                  method: "write",
                },
```
Thanks for your help.

**Comment by krirkrirk** [comment]
I see ! The ref is already a MathField and so it's too late for registering custom objects. If you're eager to, you could do a pull request to add this fonctionnality. 
The best way IMO is to pass a prop to the MathInput that has the type : 
```js
registerEmbedObjects: {id: string, htmlString: string, text: string, latex: string}[]
```
Then in MathInput.tsx, you can loop over registerEmbedObjects, and call MQ.registerEmbed for each element. 
Does that sound good to you @asianvader  ?

**Comment by asianvader** [comment]
Yes I'll be happy to create a pull request for this. Do you have a develop branch or should I do a PR to main? Thanks.

**Comment by krirkrirk** [comment]
I've accepted your PR and republished the package with your changes. Thanks ! Don't hesitate if you encouter another issue.
